### ISSUE TITLE
Privates are not downloaded

### ISSUE THREAD

**Issue by myopenissue** [gitnew2018/My-OpenPeriscope#13] opened 2019-04-17 09:26 UTC
Hi,
Privates and group broadcaste are not downloaded, please, can you check it?
thanks

**Comment by myopenissue** [comment] 2019-04-17 17:35
@gitnew2018 will you update this?

**Comment by Copelaw** [comment] 2019-04-17 19:52
really need your help! Please don't disregard

**Comment by ImControl** [comment] 2019-04-19 17:12
Same as above, after the periscope update.

**Comment by alfabetico** [comment] 2019-04-28 14:27
> 

 Basically, what Periscope did is they added AES-128 encryption to their private broadcasts. This means when you download the mpeg-ts segment files they are encrypted and you need to decrypt them before they can be played, or merged into a single .ts file.
 To decrypt the segment files you need to grab the encryption key and initialization vector from the m3u8 playlist. If you look at the playlist for a private broadcast, you will see a line above the file segment that now contains the encryptionKeyUri and IV. The encryption key is the same for each segment file, but the IV is different for each file. You need to save the key and use it, together with the IV, to decrypt each segment file.
 In Snagscope, I save all the downloaded files into this directory (sub-directory for each broadcast):
/storage/emulated/0/Android/data/com.iqtecture.app.snagscope/files
 In this directory you'll see that there is a file named encrypt.key. This is the byte[] downloaded from the encryptionKeyUri endpoint. There is also a file named "duration.list". This file contains the length(time) of each of the segment files as well as the init vector (IV) for each of the segments. We use this information to decrypt the downloaded segment files and then rename the originals to "xxx.ts.encrypted".

> 
Thanks to @KaMyKaSii

**Comment by kewalsk** [comment] 2019-05-10 20:36
I have no idea what is going on inside downloaderNode.js - there is no debug information in console about the calls this script is doing. The only calls of main script are logged. Does somebody know how to debug it? Sorry for stupid question but I'm just trying to learn javascript and node programming (actually I'm not great fan of scripting languages).

**Comment by KaMyKaSii** [comment] 2019-05-10 21:05
> I have no idea what is going on inside downloaderNode.js - there is no debug information in console about the calls this script is doing. The only calls of main script are logged. Does somebody know how to debug it? Sorry for stupid question but I'm just trying to learn javascript and node programming (actually I'm not great fan of scripting languages).

If you have nodejs installed and configured in uoir PATH, you can use [this script](https://github.com/gitnew2018/nodejs_peri_downloader)(and then use nodejs to [debug](https://nodejs.org/de/docs/guides/debugging-getting-started)it), gitnew2018 created it especially for those who used the userscript version of My-OpenPeriscope (like me) to be able to download the transmissions. The "NodeDown" button in My-OpenPeriscope copied all information already in the format required for the script (nodejs periscopeDownloader.js "link" "cookies" "output").  Currently it is only working to record public broadcasts, apparently My-OpenPeriscope is no longer able to copy the necessary cookies and even if it had (with the addition of sid=), I believe that the script would only download the encrypted chunks and join them in an unreadable ts file. Is it possible to pipe these encrypted chunks to [openssl](https://stackoverflow.com/questions/40366617/using-openssl-to-decrypt-a-ts-file) and return the decrypted result before joining them into a single ts file? Unlike you, I do not have any developmental skills.

**Comment by kewalsk** [comment] 2019-05-10 21:46
Using openssl could be good idea but I'm not sure it will work in userscript mode.

**Comment by KaMyKaSii** [comment] 2019-05-10 22:54
> Using openssl could be good idea but I'm not sure it will work in userscript mode.



> Using openssl could be good idea but I'm not sure it will work in userscript mode.

So your idea is to take advantage of the fact that MyPeriscope uses javascript (which works perfectly in browsers) to download instead of ffmpeg and allow the userscript version itself to download? I thought it would not be possible since gitnew2018 did not do this before. But the fact that private broadcasts are now encrypted and that it would require openssl to decrypt, complicates things. I researched for "openssl javascript" and have some interesting results, maybe you can take a look.  But anyway, could you first fix the "NodeDown" buttons to copy the required information in the ffmpeg syntax? I think this part is more urgent, so users of My-OpenPeriscope could continue their downloads, provided that with a terminal and ffmpeg available

**Comment by kewalsk** [comment] 2019-05-11 15:12
I added new buttons to copy the required information in the ffmpeg syntax in my fork and made pull request.
@KaMyKaSii could you please test this change before merging pull request? It is working in node but I didn't tested in userscript mode. I didn't test also all combination of different settings - this can change the way the buttons and their separators are shown.

**Comment by KaMyKaSii** [comment] 2019-05-11 15:54
> I added new buttons to copy the required information in the ffmpeg syntax in my fork and made pull request.
> @KaMyKaSii could you please test this change before merging pull request? It is working in node but I didn't tested in userscript mode. I didn't test also all combination of different settings - this can change the way the buttons and their separators are shown.

It's working but with problems.
1. Both the command name (ffmpeg) and the parameter after "-c copy" are appearing as "undefined" and consequently does not work the way it is. Is this an expected behavior (do you expect the user to explicitly set the binary name and parameter) or is it a bug?
![Screenshot_20190511-122718_1](https://user-images.githubusercontent.com/17092335/57572017-c5875400-73eb-11e9-8d1e-ef394b9e1b73.jpg)
![Screenshot_20190511-122518_1](https://user-images.githubusercontent.com/17092335/57572018-c5875400-73eb-11e9-841a-5cf9dda4dd11.jpg)

2. A request: replay links (both partial and full) are the links of api. The problem is that if you just copy the api link and try to download the replay after the transmission is deleted, it will not be possible. Could you make a request for the api link and then return the direct link to m3u8? So with the m3u8 link and the access cookie, the user can download full or partial replays even if the transmission is deleted.
3. The ffmpeg links do not appear when you activate the "repeat" check box (the function of updating links automatically from time to time), could you fix it? 
4. Have you modified any code related to the "Following2" tab?  Because it behaves strangely. Sometimes only broadcasts with available replay appears and no live streaming. Sometimes a live broadcast appears, although there are several others available (checking on Periscope app or Snagscope).
5. And another request: I do not know if this will influence something or not, but the user.js file points directly for other files, then I think it would be good if you modified it to point to these files in your repository and not to gitnew2018's.
And thank you so much for your effort!

**Comment by kewalsk** [comment] 2019-05-11 18:45
@KaMyKaSii thanks for testing
1. This is a bug of course, I did initialization of settings in part which was executed only in node version - sorry.
2. Will take a little bit more time to change but if it really works as you wrote then I'd consider this to be bug on the server side. Hopefully P* team will not fix it soon. Maybe you we shouldn't discuss technical details in public?
3. and 4. - to be fixed soon
5. I'm not sure if I understand this point correctly but if you say about lines:
`// @downloadURL ...`
`// @updateURL ..`
then I will change them, but after merge they have to be changed back.

**Comment by KaMyKaSii** [comment] 2019-05-11 19:36
> 1. This is a bug of course, I did initialization of settings in part which was executed only in node version - sorry.

You do not have to apologize, I should thank you for your willingness to help. But just a question: could you say why you chose the -movflags faststart parameter as default instead of -bsf: a aac_adtstoasc (used by the OpenPeriscope developer)? Is there any technical advantage?

> 2. Will take a little bit more time to change but if it really works as you wrote then I'd consider this to be bug on the server side. Hopefully P* team will not fix it soon. Maybe you we shouldn't discuss technical details in public?

You're right but I do not think they will fix this, if they wished they would have done it sooner. It is probably an "accidental failure" so they can take a look at deleted transmissions before actually being deleted :p

> 3 and 4. - to be fixed soon

Thanks!

> 5. I'm not sure if I understand this point correctly but if you say about lines:
// @downloadURL ...
// @updateURL ..
then I will change them, but after merge they have to be changed back.

Yes, I mean all the links pointing to files in the gitnew2018 repository. We do not know if he will ever come back to approve your pull requests, after all his last activity here was in July of last year. And if at any time he deletes the repository or account itself, it would be good if your repository is not dependent on his

**Comment by kewalsk** [comment] 2019-05-11 20:29
Fixed (except point 2), please take a look on current version. I was not able to reproduce bug from point 4 but I suppose I know what caused the strange behavior.

> why you chose the -movflags faststart parameter as default instead of -bsf: a aac_adtstoasc

This is only example how you can add more arguments. I didn't notice any difference caused by -movflags faststart. On the other hand the -bsf according to [ffmpeg documentation](https://ffmpeg.org/ffmpeg-bitstream-filters.html) is a bitstream filter - read about it and decide yourself. I'm not using it because sometimes causes big problems. The converted file is not playable. The ffmpeg is very smart and (in most cases) it's better to let him decide what to do.

> it would be good if your repository is not dependent on his

Then I will need later to change also links to the images,

**Comment by KaMyKaSii** [comment] 2019-05-11 21:20
> Fixed (except point 2), please take a look on current version. I was not able to reproduce bug from point 4 but I suppose I know what caused the strange behavior.

But are you still going to work on point 2? And yes, point 4 has been fixed, thank you. The problem is that now the "update" feature no longer works, I activate the checkbox but nothing happens.

> This is only example how you can add more arguments. I didn't notice any difference caused by -movflags faststart. On the other hand the -bsf according to [ffmpeg documentation](https://ffmpeg.org/ffmpeg-bitstream-filters.html) is a bitstream filter - read about it and decide yourself if you really need it. I'm not using any conversion because sometimes causes big problems - the converted file is not playable. The ffmpeg is very smart and (in most cases) it's better to let him decide what to do. In OpenPeriscope this parameter is added only when video is converted to mp4.

I read some of the documentation and understood that the "-bsf: aac_adtstoasc" parameter is always used when the output file is mp4.  I did not find anything about the "-movflags faststart" parameter in the official ffmpeg documentation but by external searches I understand it is used to make mp4 files be transmissible online.  Since the source format of Periscope is "MPEG-TS", would not it be best to use only the "-c copy" parameter instead of "-c copy -movflags faststart"?  To keep the file as "pure" as possible.  And it would also be nice if you could add an option to choose the output file between ts and mp4.  Once again, thank you!

**Comment by kewalsk** [comment] 2019-05-11 21:40
> But are you still going to work on point 2?

Yes I will.

> now the "update" feature no longer works

What do you mean?

> it is used to make mp4 files be streamable online

Technically it moves some data to the beginning of the file, allowing the video to be played before it is completely downloaded. This could give better results when streaming online. I will test it more and let you know about the results.

**Comment by KaMyKaSii** [comment] 2019-05-11 21:49
> What do you mean?

In My-OpenPeriscope when you enable the "Enable notifications" option the "repeat" button appears on the side of the transmissions. When you activate it, it automatically requests the "Get stream link" automatically in the same time interval as the "Notification refresh interval" setting.  But now it is not working anymore, I believe the function broke with the changes in your "Fix notifications" commit

> Technically it moves some data to the beginning of the file, allowing the video to be played before it is completely downloaded. This could give better results when streaming online. I will test it more and let you know about the results.
All right

**Comment by kewalsk** [comment] 2019-05-11 22:09
>>  now the "update" feature no longer works

OK I will take a look on this. 
I believe I didn't touch the existing functionality so the links should work as you described in them. Can you check and confirm which button gives the proper link now (if any)?

>  To keep the file as "pure" as possible.

Yes, you can just delete this option in settings. This is only default value for new user.

> And it would also be nice if you could add an option to choose the output file between ts and mp4.

I can do that but really I don't recommend to convert into mp4 on the fly. It is better to do it later if you need. Converting on the fly give unplayable video when the download process is broken and there is a little chance to fix it. I already mentioned about that problem in OpenPeriscope project issue [#68](https://github.com/Pmmlabs/OpenPeriscope/issues/68)

**Comment by KaMyKaSii** [comment] 2019-05-12 00:26
> Can you check and confirm which button gives the proper link now (if any)?

I did not understand your question. The "Get stream link" button still works perfectly, the problem is that the "repeat" checkbox to automate the action of getting these (updated) links (even with the browser in the background) is no longer working. One thing I noticed is that before, when I opened My-OpenPeriscope (the original of gitnew2018) and opened the "Following2" tab, all the available replays automatically showed the download links, but now no more, I believe that the two  problems are related.

> I can do that but really I don't recommend to convert into mp4 on the fly. It is better to do it later if you need. Converting on the fly give unplayable video when the download process is broken and there is a little chance to fix it. I already mentioned about that problem in OpenPeriscope project issue [#68](https://github.com/Pmmlabs/OpenPeriscope/issues/68)

You're right, I've already suffered some problems by downloading directly to mp4

**Comment by kewalsk** [comment] 2019-05-12 09:26
I created separate issues in my fork for all bugs and requests to my version, because this thread becomes unreadable and is starting to be unrelated the original topic.

Part of them already closed.

I belive only issues: 
https://github.com/kewalsk/My-OpenPeriscope/issues/2 
https://github.com/kewalsk/My-OpenPeriscope/issues/5
https://github.com/kewalsk/My-OpenPeriscope/issues/6
remains to be done.

**Comment by myopenissue** [comment] 2019-05-24 17:09
Hey, did you get the privates works again?

**Comment by kewalsk** [comment] 2019-05-24 19:08
Yes but not in this app. Use ffmpg for downloading.

**Comment by Kamouser** [comment] 2019-05-25 07:02
@kewalsk ffmpeg unlike the script downloaderNode. js sometimes download TS transmissions with bug, example the length of time of the video. Duration: 23:18:24.
and downloaderNode.JS performed it correctly
Is there any command in ffmpeg that can correct the duration of the video as downloaderNode. js?

**Comment by kewalsk** [comment] 2019-05-25 08:48
@Kamouser I have no idea. The option `-movflags faststart` is apparently not a solution.
I believe the problem should be addressed to [ffmpeg](https://ffmpeg.org/bugreports.html) developers. 
I suppose when you have video downloaded, reenconding it should help but I didn't tried.

**Comment by myopenissue** [comment] 2019-05-27 08:15
Which version works? Your fork? Do you have any binaries to be used?

**Comment by kewalsk** [comment] 2019-05-27 16:18
Both works, just don't use binary with old ffmpeg version included. I don't have release binaries.

**Comment by Kamouser** [comment] 2019-05-29 19:15
Hi @kewalsk Any commands or programs to repair the. mp4 files that contain only the weight and not the duration? When they cannot be played video

**Comment by kewalsk** [comment] 2019-05-30 13:38
Try to use ffmpeg to convert video into mp4. I don't know for sure it will help (I don't care about the duration shown in player).

**Closed** 2019-06-29 13:35 UTC
